### ISSUE TITLE
shape of checkpoint doesn't match(might be wrongly uploaded?)

### ISSUE THREAD

**Issue by hongxianglics** [wangyu-sd/MechRetro#4]
Hi Yu,

I encounter this problem which said the checkpoints are not found:

<img width="728" alt="捕获" src="https://user-images.githubusercontent.com/104338096/203839960-01797fd1-fb2d-48bf-8ada-c97e5f615412.PNG">

I then check the origin python file RetroAGT.py 

<img width="541" alt="捕获2" src="https://user-images.githubusercontent.com/104338096/203840186-c8bb5aa9-a4ab-44b7-bd22-b38b338dcc11.PNG">

In the model_dump variable, I thought the checkpoints might be the "multistep check point"`model_for_multi_step.ckpt`,so I merely change the path.

But later I encounter this problem shows the shape of the checkpoint and the model doesn't match, which indicates I might used wrong checkpoints.
<img width="731" alt="捕获3" src="https://user-images.githubusercontent.com/104338096/203840714-f7740bf2-3092-4f2b-a37d-7cb047e58d7a.PNG">

So I wonder that if you can check what is the correct checkpoints for `model_dump` in `RetroAGT.py `

Very much thanks in advance!

**Comment by wangyu-sd** [comment]
Hi,
For Q1 : Yes, what you modified is right. We have commited the corrected code. Thanks for your issue.
For Q2 : I feel sorry that  we cannot reproduce the error you encountered. But I guess that you may wrongly load the vocabulary of collected leaving group. In this circumstance, you can wait for the file `leaving_group.pt` that we are updating (it may takes a few hours due to the slowness of the network in my region), and put it under the folder `data/multi-step/`.  And soon, we will update the README file attaching with this url. Thanks for the contribute you propose.

Best

**Comment by hongxianglics** [comment]
Hi Yu,

The new file works! I appreciate for your quick response and great help!

Have a great day!
